# Generated by Django 4.0.6 on 2022-07-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Человекопонятный URL (само генерация)'),
        ),
    ]
