# Generated by Django 4.0.6 on 2022-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_slug_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
