# Generated by Django 4.0.6 on 2022-07-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currency',
            field=models.CharField(choices=[('KGZ', 'KGZ'), ('USD', 'USD'), ('EURO', 'EURO'), ('RUB', 'RUB'), ('Договорная', 'Договорная')], default='Договорная', max_length=100),
        ),
    ]
